### ISSUE TITLE
Create ODK for CAP helper ontology

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/cap-pipeline-config#60]
AIM: An ODK based repo that allows us to finely tailor content for loading into the KB and also to manage content generated for CAP

Examples:
* We currently use a single term from PATO and importing all of PATO has some potential to lead to clashes between imports.  We can therefore set up ODK to import just the term we need.
* EFO potentially brings in problematic content, even if using the base file, so a simple module extraction for terms we need would also be good.
* We can manage the robot build of the CAP organ slim through robot template build support in ODK.

**Comment by dosumis** [comment]
@ubyndr to implement, but @bvarner-ebi should join to observe.

**Comment by evanbiederstedt** [comment]
@ubyndr The above roughly makes sense to me. Please assign me to any PRs for review. 

Let's also discuss in-person at the next Ugur-Evan 1-on-1 meeting

**Comment by evanbiederstedt** [comment]
In fact, this ODK idea is very very good. This might be able to replace the Google Spreadsheet idea we had for @mfutey and @arapoff to review published datasets. 

CC @ilguzin

**Comment by ubyndr** [comment]
Created a simple repo at [kharchenkolab/cap_ontology](https://github.com/kharchenkolab/cap_ontology)  with following config;
```
id: capo
title: "CAP Ontology"
github_org: kharchenkolab
git_main_branch: main
repo: cap_ontology
use_dosdps: TRUE
release_artefacts: 
  - base
  - full
  - simple
primary_release: full
export_formats:
  - owl
  - obo
  - json
import_group:
  products: 
    - id: ro
    - id: pato
robot_java_args: '-Xmx8G'
```

I thought I would need to determine the imports and exact terms to start with but it seems I just needed to create an initial repo to work with. Sorry for my misunderstanding.
