### ISSUE TITLE
Rerunning write_organ_tags.py re-sorts the classes

### ISSUE THREAD

**Issue by ghost** [EBISPOT/cap-pipeline-config#83]
See conversation in #82.

Rerunning write_organ_tags.py re-sorts the classes (seemingly in a random order) in neo4j2owl-config.yaml. I don't think this has a downstream impact, but noting it as an FYI.

I also see that sometimes the DL queries under the classes are in different orders (see below). Again, I don't think this has any impact but am noting as an FYI.

```
  - classes:
      - RO:0002131 some UBERON:0002113
      - UBERON:0002113
    label: kidney
  - classes:
      - UBERON:0001705
      - RO:0002131 some UBERON:0001705
    label: nail
```
