### ISSUE TITLE
Split Developmental_stage tag into multiple tags based on organisms

### ISSUE THREAD

**Issue by ubyndr** [EBISPOT/cap-pipeline-config#89]
Since we have contextual search integrated and David mention on people desire to see cell types of organisms other than humans, I think we should split up the following config into separated tags based on organisms;
```YAML
  - classes:
      - UBERON:0000105
      - FBdv:00007012
      - WBls:0000075
      - ZFS:0100000
      - MmusDv:0000000
      - HsapDv:0000000
      - XAO:1000000
    label: Developmental_stage
```
What do you think about this change @dosumis , @evanbiederstedt and @bvarner-ebi ?
